def label = "${UUID.randomUUID().toString()}"

/* -------- functions ---------- */
def notifySlack(STATUS, COLOR) {
/*
	slackSend (color: COLOR, message: STATUS+" : " +  "${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL})")
*/
}

def emailRecipients="happycloudpak@gmail.com"
def notifyMail(STATUS, RECIPIENTS) {
/*
	emailext body: STATUS+" : " +  "${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL})",
	subject: STATUS + " : " + "${env.JOB_NAME} [${env.BUILD_NUMBER}]",
	from: "happycloudpak@gmail.com",
	to: RECIPIENTS
*/
}

/* ------------------------------ */

notifySlack("STARTED", "#FFFF00")
notifyMail("STARTED", "${emailRecipients}")

//node(label) {
node {
    String stageName = ""
    
    stageName = "Get Source"	
    stage(stageName) {
        echo "**** START : " + stageName
        
        git url: "https://github.com/happykube/api-service.git", branch: "main"
        // git url: "https://github.com/devJacob01/springcloud.git", branch: "master", credentialsId: "auth_gitlab"	
    }

    //-- 환경변수 파일 읽어서 변수값 셋팅
    def props = readProperties  file:"./cicd/pipeline.properties"  

    def imageRegistry = props["imageResgistry"]
    def imageOrganization = props["imageOrganization"]
    def imageRepository = props["imageRepository"]
    def imageTag = props["imageTag"]

    def dockerRegistry = props["dockerRegistry"]
    def credentialRegistry=props["credentialRegistry"]
    
    def baseDir = props["baseDir"]
    def baseDeployDir = props["baseDeployDir"]
    def skipStages = props["skipStages"]
    
    def sonarQubeURL = props["sonarQubeURL"]
    def sonarQubeLogin = props["sonarQubeLogin"]
    def sonarQubeProject = props["sonarQubeProject"]
    
    // tag를 재정의 함. 이미지 버전이 달라야 배포시 컨테이너에서 인식
    def timeStamp = System.currentTimeMillis()
    echo "TimeStamp: ${timeStamp}"
    echo "Tag : ${imageTag}"
    tag = imageTag+"-"+timeStamp
    echo "New Tag : ${tag}"
    
    try {
        stageName = "Inspection Code"
        stage(stageName) {
            echo "**** START : " + stageName
            if("${skipStages}".contains(stageName)) {
                echo "Skipped: " + stageName
            } else {
                script {
                    dir("${env.WORKSPACE}/${baseDir}"){  // change directory
                        sh ("pwd")
                        sh ("mvn sonar:sonar \
                            -Dsonar.projectKey=${icpSonarQubeProject}  \
                            -Dsonar.projectName=${icpSonarQubeProject} \
                            -Dsonar.host.url=${icpSonarQubeURL} \
                            -Dsonar.login=${icpSonarQubeLogin}")
                    }
                }				
            }
        }

        stageName = "Get CI/CD files"
        stage(stageName) {
            script {
                sh "cd ${env.WORKSPACE}"
                sh "if [ -f ${env.WORKSPACE}/run-cicd/cmd/run-cicd ]; then rm -rf run-cicd; fi"
                sh "git clone https://github.com/happykube/run-cicd.git"
            }
        }

        stageName = "Build"
        stage(stageName) {
            echo "**** START : " + stageName           
            script {                
                sh "cd ${env.WORKSPACE}/${baseDir}"
                sh "${env.WORKSPACE}/run-cicd/cmd/build-image happycloudpak happy@cloud . java ${env.WORKSPACE}/run-cicd"
            }
        }

        stageName = "Copy CI/CD Scripts to bastion"
        stage(stageName) {
            script {
                sh "ssh bastion mkdir -p /root/cicd/${imageRepository}"
                sh "scp -r ${env.WORKSPACE}/run-cicd bastion:/root/"
                sh "scp -r ${env.WORKSPACE}/cicd bastion:/root/cicd/${imageRepository}/"
            }
        }

        stageName = "Deploy"
        stage(stageName) {
            script {
                sh "ssh bastion mkdir -p /root/cicd/${imageRepository}/deploy"
                sh "ssh bastion /root/run-cicd/cmd/deploy . dev /root/cicd/${imageRepository}"
            }
        }
        
        echo "**** FINISH ALL STAGES : SUCESS"
                    
        notifySlack("${currentBuild.currentResult}", "#00FF00")
        notifyMail("${currentBuild.currentResult}", "${emailRecipients}")
    } catch(e) {
        currentBuild.result = "FAILED"
        notifySlack("${currentBuild.currentResult}", "#FF0000")
        notifyMail("${currentBuild.currentResult}", "${emailRecipients}")			
    }
}